version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10-buster # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run: echo $CACHE_VERSION
      - run: yarn global add node-gyp && yarn install

      - save_cache:
          paths: -node_modules
          key:
            - {{ .Environment.CACHE_VERSION }}-dependencies-{{ checksum "package.json" }}
  lint:
    docker:
      - image: circleci/node:10-buster
    steps:
      - checkout # check out the code in the project directory
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run: yarn lint

  format:
    docker:
      - image: circleci/node:10-buster
    steps:
      - checkout # check out the code in the project directory
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run: yarn format:check
  test:
    docker:
      - image: circleci/node:10-buster
    steps:
      - checkout # check out the code in the project directory
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run: yarn test:ci
workflows:
  version: 1
  build_and_test:
    jobs:
      - build
      - lint
      - format
      - test
