version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10-buster # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run: yarn global add node-gyp && yarn install
      - save_cache:
          paths: node_modules
          key: dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
  lint:
    docker:
      - image: circleci/node:10-buster
    steps:
      - checkout # check out the code in the project directory
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run: yarn lint
  format:
    docker:
      - image: circleci/node:10-buster
    steps:
      - checkout # check out the code in the project directory
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run: yarn format:check
  test:
    docker:
      - image: circleci/node:10-buster
    steps:
      - checkout # check out the code in the project directory
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run: yarn test:ci
  e2e:
    docker:
      - image: circleci/node:10-buster
      - image: postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: psqluer
          POSTGRES_PASSOWRD: psqlpassword
          POSTGRES_DB: psdb
    steps:
      - checkout # check out the code in the project directory
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run:
          command: yarn test:e2e
          environment:
            DATABASE_URL: postgres://psqluer:psqlpassword@localhost:5432/psdb
            JWT_SECRET: "TOTO"
            API_PORT: 3000
            API_HOST: localhost
            API_PROTOCOL: http
  docker-build:
    machine: true
    steps:
      - checkout
      - run:
          command: echo "$DOCKER_PSWD" |  docker login -u "aberthier15" --password-stdin
      - run:
          name: build docker
          command: docker build  --tag aberthier15/app:1.0.1 .
      - run:
          name: docker push 
          command: docker push aberthier15/app:1.0.1
  doc:
    docker:
      - image: circleci/node:10-buster
    steps:
      - checkout # check out the code in the project directory
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run:
          name: yarn Doc
          command: yarn generate module with-crud --name server-doc
      - store_artifacts:
          path: server-doc
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - lint:
          requires:
            - build
      - format:
          requires:
            - build
      - test:
          requires:
            - build
      - e2e:
          requires:
            - build
      - docker-build:
          requires:
            - lint
            - test
          filters:
            branches:
              only: master
      - doc:
          requires:
            - lint
            - test
            - e2e
