 version: 2.1
 jobs:
    build:
        docker: 
            - image: circleci/node:10-buster # the primary container, where your job's commands are run
        steps:
            - checkout # check out the code in the project directory
            - run: yarn global add node-gyp && yarn install
            - run: yarn lint && yarn format:check
            - run: yarn test:ci